--Create Roles as !Securityadmin!: 
 USE ROLE SECURITYADMIN; 
 
CREATE ROLE IF NOT EXISTS ACC_PROD_ADMIN_1;
CREATE ROLE IF NOT EXISTS ACC_PROD_ANALYST;
CREATE ROLE IF NOT EXISTS ACC_PROD_DEVOPS;
CREATE ROLE IF NOT EXISTS ACC_DEV_ADMIN;
CREATE ROLE IF NOT EXISTS ACC_DEV_DEVELOPER;
CREATE ROLE IF NOT EXISTS ACC_ELT_PROD;
CREATE ROLE IF NOT EXISTS ACC_DEV_DEVOPS;
CREATE ROLE IF NOT EXISTS FN_DEV_MANAGER;
CREATE ROLE IF NOT EXISTS FN_PROD_MANAGER;
 
 --Grant role to Parent Role 
GRANT ROLE ACC_PROD_ADMIN_1 TO ROLE SYSADMIN;
GRANT ROLE ACC_PROD_ANALYST TO ROLE SYSADMIN;
GRANT ROLE ACC_PROD_DEVOPS TO ROLE FN_PROD_MANAGER;
GRANT ROLE ACC_DEV_ADMIN TO ROLE SYSADMIN;
GRANT ROLE ACC_DEV_DEVELOPER TO ROLE FN_DEV_MANAGER;
GRANT ROLE ACC_ELT_PROD TO ROLE SYSADMIN;
GRANT ROLE ACC_DEV_DEVOPS TO ROLE FN_DEV_MANAGER;
GRANT ROLE FN_DEV_MANAGER TO ROLE SYSADMIN;
GRANT ROLE FN_PROD_MANAGER TO ROLE SYSADMIN;
 
 -- RBAC script: 

--New Role :::

--New Schema FINANCE
USE ROLE SYSADMIN; 
 GRANT CREATE DATABASE, CREATE WAREHOUSE ON ACCOUNT TO ACC_PROD_ADMIN_1;
GRANT ALL ON DATABASE ARBAC_PROD_DB TO ROLE ACC_PROD_ADMIN_1;
GRANT ALL ON ALL SCHEMAS IN DATABASE ARBAC_PROD_DB TO ROLE ACC_PROD_ADMIN_1;

--New Schema COMMERCE
USE ROLE SYSADMIN; 
 GRANT CREATE DATABASE, CREATE WAREHOUSE ON ACCOUNT TO ACC_PROD_ADMIN_1;
GRANT ALL ON DATABASE ARBAC_PROD_DB TO ROLE ACC_PROD_ADMIN_1;
GRANT ALL ON ALL SCHEMAS IN DATABASE ARBAC_PROD_DB TO ROLE ACC_PROD_ADMIN_1;

--New Schema FEDERAL
USE ROLE SYSADMIN; 
 GRANT CREATE DATABASE, CREATE WAREHOUSE ON ACCOUNT TO ACC_PROD_ADMIN_1;
GRANT ALL ON DATABASE ARBAC_PROD_DB TO ROLE ACC_PROD_ADMIN_1;
GRANT ALL ON ALL SCHEMAS IN DATABASE ARBAC_PROD_DB TO ROLE ACC_PROD_ADMIN_1;

--New Schema PHI
USE ROLE SYSADMIN; 
 GRANT CREATE DATABASE, CREATE WAREHOUSE ON ACCOUNT TO ACC_PROD_ADMIN_1;
GRANT ALL ON DATABASE ARBAC_PROD_DB TO ROLE ACC_PROD_ADMIN_1;
GRANT ALL ON ALL SCHEMAS IN DATABASE ARBAC_PROD_DB TO ROLE ACC_PROD_ADMIN_1;

USE ROLE SYSADMIN; 
 GRANT USAGE, OPERATE ON WAREHOUSES WH_PROD_SMALL TO ROLE ACC_PROD_ADMIN_1;

--New Role :::

--New Schema FINANCE
USE ROLE SYSADMIN;-- Or role assigned to perform this 
 GRANT USAGE ON DATABASE ARBAC_PROD_DB TO ROLE ACC_PROD_ANALYST ;
USE ROLE ARBAC_P_ADMIN_ROLE;
GRANT USAGE ON SCHEMA ARBAC_PROD_DB.FINANCE TO ROLE ACC_PROD_ANALYST;

GRANT SELECT ON ALL TABLES IN SCHEMA ARBAC_PROD_DB.FINANCE TO ROLE ACC_PROD_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ARBAC_PROD_DB.FINANCE TO ROLE ACC_PROD_ANALYST;

--New Schema COMMERCE
USE ROLE SYSADMIN;-- Or role assigned to perform this 
 GRANT USAGE ON DATABASE ARBAC_PROD_DB TO ROLE ACC_PROD_ANALYST ;
USE ROLE ARBAC_P_ADMIN_ROLE;
GRANT USAGE ON SCHEMA ARBAC_PROD_DB.COMMERCE TO ROLE ACC_PROD_ANALYST;

GRANT SELECT ON ALL TABLES IN SCHEMA ARBAC_PROD_DB.COMMERCE TO ROLE ACC_PROD_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ARBAC_PROD_DB.COMMERCE TO ROLE ACC_PROD_ANALYST;

--New Schema FEDERAL
USE ROLE SYSADMIN;-- Or role assigned to perform this 
 GRANT USAGE ON DATABASE ARBAC_PROD_DB TO ROLE ACC_PROD_ANALYST ;
USE ROLE ARBAC_P_ADMIN_ROLE;
GRANT USAGE ON SCHEMA ARBAC_PROD_DB.FEDERAL TO ROLE ACC_PROD_ANALYST;

GRANT SELECT ON ALL TABLES IN SCHEMA ARBAC_PROD_DB.FEDERAL TO ROLE ACC_PROD_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ARBAC_PROD_DB.FEDERAL TO ROLE ACC_PROD_ANALYST;

--New Schema PHI
USE ROLE SYSADMIN;-- Or role assigned to perform this 
 GRANT USAGE ON DATABASE ARBAC_PROD_DB TO ROLE ACC_PROD_ANALYST ;
USE ROLE ARBAC_P_ADMIN_ROLE;
GRANT USAGE ON SCHEMA ARBAC_PROD_DB.PHI TO ROLE ACC_PROD_ANALYST;

GRANT SELECT ON ALL TABLES IN SCHEMA ARBAC_PROD_DB.PHI TO ROLE ACC_PROD_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ARBAC_PROD_DB.PHI TO ROLE ACC_PROD_ANALYST;

USE ROLE SYSADMIN; 
 GRANT USAGE, OPERATE ON WAREHOUSES WH_PROD_LARGE TO ROLE ACC_PROD_ANALYST;

--New Role :::

--New Schema FINANCE
USE ROLE SYSADMIN;-- Or role assigned to perform this 
 GRANT USAGE ON DATABASE ARBAC_PROD_DB TO ROLE ACC_PROD_DEVOPS ;
USE ROLE ARBAC_P_ADMIN_ROLE;
GRANT ALL ON SCHEMA ARBAC_PROD_DB.FINANCE TO ROLE ACC_PROD_DEVOPS;

GRANT SELECT ON ALL TABLES IN SCHEMA ARBAC_PROD_DB.FINANCE TO ROLE ACC_PROD_DEVOPS;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ARBAC_PROD_DB.FINANCE TO ROLE ACC_PROD_DEVOPS;

--New Schema COMMERCE
USE ROLE SYSADMIN;-- Or role assigned to perform this 
 GRANT USAGE ON DATABASE ARBAC_PROD_DB TO ROLE ACC_PROD_DEVOPS ;
USE ROLE ARBAC_P_ADMIN_ROLE;
GRANT ALL ON SCHEMA ARBAC_PROD_DB.COMMERCE TO ROLE ACC_PROD_DEVOPS;

GRANT SELECT ON ALL TABLES IN SCHEMA ARBAC_PROD_DB.COMMERCE TO ROLE ACC_PROD_DEVOPS;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ARBAC_PROD_DB.COMMERCE TO ROLE ACC_PROD_DEVOPS;

--New Schema FEDERAL
USE ROLE SYSADMIN;-- Or role assigned to perform this 
 GRANT USAGE ON DATABASE ARBAC_PROD_DB TO ROLE ACC_PROD_DEVOPS ;
USE ROLE ARBAC_P_ADMIN_ROLE;
GRANT ALL ON SCHEMA ARBAC_PROD_DB.FEDERAL TO ROLE ACC_PROD_DEVOPS;

GRANT SELECT ON ALL TABLES IN SCHEMA ARBAC_PROD_DB.FEDERAL TO ROLE ACC_PROD_DEVOPS;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ARBAC_PROD_DB.FEDERAL TO ROLE ACC_PROD_DEVOPS;

--New Schema PHI
USE ROLE SYSADMIN;-- Or role assigned to perform this 
 GRANT USAGE ON DATABASE ARBAC_PROD_DB TO ROLE ACC_PROD_DEVOPS ;
USE ROLE ARBAC_P_ADMIN_ROLE;
GRANT ALL ON SCHEMA ARBAC_PROD_DB.PHI TO ROLE ACC_PROD_DEVOPS;

GRANT SELECT ON ALL TABLES IN SCHEMA ARBAC_PROD_DB.PHI TO ROLE ACC_PROD_DEVOPS;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ARBAC_PROD_DB.PHI TO ROLE ACC_PROD_DEVOPS;

USE ROLE SYSADMIN; 
 GRANT USAGE, OPERATE ON WAREHOUSES WH_PROD_MID TO ROLE ACC_PROD_DEVOPS;

--New Role :::

--New Schema FINANCE
USE ROLE SYSADMIN; 
 GRANT CREATE DATABASE, CREATE WAREHOUSE ON ACCOUNT TO ACC_DEV_ADMIN;
GRANT ALL ON DATABASE ARBAC_TEST_DB TO ROLE ACC_DEV_ADMIN;
GRANT ALL ON ALL SCHEMAS IN DATABASE ARBAC_TEST_DB TO ROLE ACC_DEV_ADMIN;

--New Schema COMMERCE
USE ROLE SYSADMIN; 
 GRANT CREATE DATABASE, CREATE WAREHOUSE ON ACCOUNT TO ACC_DEV_ADMIN;
GRANT ALL ON DATABASE ARBAC_TEST_DB TO ROLE ACC_DEV_ADMIN;
GRANT ALL ON ALL SCHEMAS IN DATABASE ARBAC_TEST_DB TO ROLE ACC_DEV_ADMIN;

--New Schema FEDERAL
USE ROLE SYSADMIN; 
 GRANT CREATE DATABASE, CREATE WAREHOUSE ON ACCOUNT TO ACC_DEV_ADMIN;
GRANT ALL ON DATABASE ARBAC_TEST_DB TO ROLE ACC_DEV_ADMIN;
GRANT ALL ON ALL SCHEMAS IN DATABASE ARBAC_TEST_DB TO ROLE ACC_DEV_ADMIN;

--New Schema PHI
USE ROLE SYSADMIN; 
 GRANT CREATE DATABASE, CREATE WAREHOUSE ON ACCOUNT TO ACC_DEV_ADMIN;
GRANT ALL ON DATABASE ARBAC_TEST_DB TO ROLE ACC_DEV_ADMIN;
GRANT ALL ON ALL SCHEMAS IN DATABASE ARBAC_TEST_DB TO ROLE ACC_DEV_ADMIN;

USE ROLE SYSADMIN; 
 GRANT USAGE, OPERATE ON WAREHOUSES WH_PROD_SMALL TO ROLE ACC_DEV_ADMIN;

--New Role :::

--New Schema FINANCE
USE ROLE SYSADMIN;-- Or role assigned to perform this 
 GRANT USAGE ON DATABASE ARBAC_TEST_DB TO ROLE ACC_DEV_DEVELOPER ;
USE ROLE ARBAC_T_ADMIN_ROLE;
GRANT USAGE ON SCHEMA ARBAC_TEST_DB.FINANCE TO ROLE ACC_DEV_DEVELOPER;

GRANT ALL ON ALL TABLES IN SCHEMA ARBAC_TEST_DB.FINANCE TO ROLE ACC_DEV_DEVELOPER;
GRANT ALL ON FUTURE TABLES IN SCHEMA ARBAC_TEST_DB.FINANCE TO ROLE ACC_DEV_DEVELOPER;

--New Schema COMMERCE
USE ROLE SYSADMIN;-- Or role assigned to perform this 
 GRANT USAGE ON DATABASE ARBAC_TEST_DB TO ROLE ACC_DEV_DEVELOPER ;
USE ROLE ARBAC_T_ADMIN_ROLE;
GRANT USAGE ON SCHEMA ARBAC_TEST_DB.COMMERCE TO ROLE ACC_DEV_DEVELOPER;

GRANT ALL ON ALL TABLES IN SCHEMA ARBAC_TEST_DB.COMMERCE TO ROLE ACC_DEV_DEVELOPER;
GRANT ALL ON FUTURE TABLES IN SCHEMA ARBAC_TEST_DB.COMMERCE TO ROLE ACC_DEV_DEVELOPER;

--New Schema FEDERAL
USE ROLE SYSADMIN;-- Or role assigned to perform this 
 GRANT USAGE ON DATABASE ARBAC_TEST_DB TO ROLE ACC_DEV_DEVELOPER ;
USE ROLE ARBAC_T_ADMIN_ROLE;
GRANT ALL ON SCHEMA ARBAC_TEST_DB.FEDERAL TO ROLE ACC_DEV_DEVELOPER;

GRANT ALL ON ALL TABLES IN SCHEMA ARBAC_TEST_DB.FEDERAL TO ROLE ACC_DEV_DEVELOPER;
GRANT ALL ON FUTURE TABLES IN SCHEMA ARBAC_TEST_DB.FEDERAL TO ROLE ACC_DEV_DEVELOPER;

--New Schema PHI
USE ROLE SYSADMIN;-- Or role assigned to perform this 
 GRANT USAGE ON DATABASE ARBAC_TEST_DB TO ROLE ACC_DEV_DEVELOPER ;
USE ROLE ARBAC_T_ADMIN_ROLE;
GRANT ALL ON SCHEMA ARBAC_TEST_DB.PHI TO ROLE ACC_DEV_DEVELOPER;

GRANT ALL ON ALL TABLES IN SCHEMA ARBAC_TEST_DB.PHI TO ROLE ACC_DEV_DEVELOPER;
GRANT ALL ON FUTURE TABLES IN SCHEMA ARBAC_TEST_DB.PHI TO ROLE ACC_DEV_DEVELOPER;

USE ROLE SYSADMIN; 
 GRANT USAGE, OPERATE ON WAREHOUSES WH_PROD_MID TO ROLE ACC_DEV_DEVELOPER;

--New Role :::

--New Schema FINANCE
USE ROLE SYSADMIN;-- Or role assigned to perform this 
 GRANT USAGE ON DATABASE ARBAC_PROD_DB TO ROLE ACC_ELT_PROD ;
USE ROLE ARBAC_P_ADMIN_ROLE;
GRANT USAGE ON SCHEMA ARBAC_PROD_DB.FINANCE TO ROLE ACC_ELT_PROD;

GRANT INSERT, UPDATE, DELETE, REFERENCES ON ALL TABLES IN SCHEMA ARBAC_PROD_DB.FINANCE TO ROLE ACC_ELT_PROD;
GRANT INSERT, UPDATE, DELETE on future tables in schema ARBAC_PROD_DB.FINANCE TO ROLE ACC_ELT_PROD;

--New Schema COMMERCE
USE ROLE SYSADMIN;-- Or role assigned to perform this 
 GRANT USAGE ON DATABASE ARBAC_PROD_DB TO ROLE ACC_ELT_PROD ;
USE ROLE ARBAC_P_ADMIN_ROLE;
GRANT USAGE ON SCHEMA ARBAC_PROD_DB.COMMERCE TO ROLE ACC_ELT_PROD;

GRANT ALL ON ALL TABLES IN SCHEMA ARBAC_PROD_DB.COMMERCE TO ROLE ACC_ELT_PROD;
GRANT ALL ON FUTURE TABLES IN SCHEMA ARBAC_PROD_DB.COMMERCE TO ROLE ACC_ELT_PROD;

--New Schema FEDERAL
USE ROLE SYSADMIN;-- Or role assigned to perform this 
 GRANT USAGE ON DATABASE ARBAC_PROD_DB TO ROLE ACC_ELT_PROD ;
USE ROLE ARBAC_P_ADMIN_ROLE;
GRANT USAGE ON SCHEMA ARBAC_PROD_DB.FEDERAL TO ROLE ACC_ELT_PROD;




--New Schema PHI
USE ROLE SYSADMIN;-- Or role assigned to perform this 
 GRANT USAGE ON DATABASE ARBAC_PROD_DB TO ROLE ACC_ELT_PROD ;
USE ROLE ARBAC_P_ADMIN_ROLE;
GRANT USAGE ON SCHEMA ARBAC_PROD_DB.PHI TO ROLE ACC_ELT_PROD;




USE ROLE SYSADMIN; 
 GRANT USAGE, OPERATE ON WAREHOUSES WH_PROD_MID TO ROLE ACC_ELT_PROD;

--New Role :::

--New Schema FINANCE
USE ROLE SYSADMIN;-- Or role assigned to perform this 
 GRANT USAGE ON DATABASE ARBAC_TEST_DB TO ROLE ACC_DEV_DEVOPS ;
USE ROLE ARBAC_T_ADMIN_ROLE;
GRANT ALL ON SCHEMA ARBAC_TEST_DB.FINANCE TO ROLE ACC_DEV_DEVOPS;

GRANT ALL ON ALL TABLES IN SCHEMA ARBAC_TEST_DB.FINANCE TO ROLE ACC_DEV_DEVOPS;
GRANT ALL ON FUTURE TABLES IN SCHEMA ARBAC_TEST_DB.FINANCE TO ROLE ACC_DEV_DEVOPS;

--New Schema COMMERCE
USE ROLE SYSADMIN;-- Or role assigned to perform this 
 GRANT USAGE ON DATABASE ARBAC_TEST_DB TO ROLE ACC_DEV_DEVOPS ;
USE ROLE ARBAC_T_ADMIN_ROLE;
GRANT ALL ON SCHEMA ARBAC_TEST_DB.COMMERCE TO ROLE ACC_DEV_DEVOPS;

GRANT ALL ON ALL TABLES IN SCHEMA ARBAC_TEST_DB.COMMERCE TO ROLE ACC_DEV_DEVOPS;
GRANT ALL ON FUTURE TABLES IN SCHEMA ARBAC_TEST_DB.COMMERCE TO ROLE ACC_DEV_DEVOPS;

--New Schema FEDERAL
USE ROLE SYSADMIN;-- Or role assigned to perform this 
 GRANT USAGE ON DATABASE ARBAC_TEST_DB TO ROLE ACC_DEV_DEVOPS ;
USE ROLE ARBAC_T_ADMIN_ROLE;
GRANT ALL ON SCHEMA ARBAC_TEST_DB.FEDERAL TO ROLE ACC_DEV_DEVOPS;

GRANT ALL ON ALL TABLES IN SCHEMA ARBAC_TEST_DB.FEDERAL TO ROLE ACC_DEV_DEVOPS;
GRANT ALL ON FUTURE TABLES IN SCHEMA ARBAC_TEST_DB.FEDERAL TO ROLE ACC_DEV_DEVOPS;

--New Schema PHI
USE ROLE SYSADMIN;-- Or role assigned to perform this 
 GRANT USAGE ON DATABASE ARBAC_TEST_DB TO ROLE ACC_DEV_DEVOPS ;
USE ROLE ARBAC_T_ADMIN_ROLE;
GRANT ALL ON SCHEMA ARBAC_TEST_DB.PHI TO ROLE ACC_DEV_DEVOPS;

GRANT ALL ON ALL TABLES IN SCHEMA ARBAC_TEST_DB.PHI TO ROLE ACC_DEV_DEVOPS;
GRANT ALL ON FUTURE TABLES IN SCHEMA ARBAC_TEST_DB.PHI TO ROLE ACC_DEV_DEVOPS;

USE ROLE SYSADMIN; 
 GRANT USAGE, OPERATE ON WAREHOUSES WH_PROD_SMALL TO ROLE ACC_DEV_DEVOPS;

--New Role :::

USE ROLE SYSADMIN; 
 GRANT USAGE, OPERATE ON WAREHOUSES WH_PROD_SMALL TO ROLE FN_DEV_MANAGER;

--New Role :::

USE ROLE SYSADMIN; 
 GRANT USAGE, OPERATE ON WAREHOUSES WH_PROD_SMALL TO ROLE FN_PROD_MANAGER;
